Repository elementary/gala, pull requests merged in 2021-11, with the labels that each got.

#1234 Bring "Catts" in-tree
  src/Widgets/RoundedActor.vala
  src/Widgets/WindowSwitcher.vala
  src/meson.build
Labels: Needs Design

#1275 Multitasking View: Show nudge animation only on the primary display
  src/WindowManager.vala
Labels: Bitesize

#1289 Use current monitor instead of primary monitor for WindowSwitcher
  src/Widgets/WindowSwitcher.vala
Labels: Bitesize

#1290 WindowManager: handle empty action keys
  src/WindowManager.vala
Labels: Bitesize

#1293 Tooltip: null check text_actor before removing
  src/Widgets/Tooltip.vala
Labels: Bitesize

#1303 Control: Remove plank build dep
  debian/control
Labels: Bitesize

#1304 WindowManager: don't type check when undim
  src/WindowManager.vala
Labels: Bitesize

#1276 Release 6.3.0
  data/gala.appdata.xml.in
  meson.build
Labels: Release

#1318 WindowSwitcher: Clear indicator background
  src/Widgets/WindowSwitcher.vala
Labels: Bitesize
