Repository elementary/gala, pull requests merged in 2021-09, with the labels that each got.

#1250 Fix crash changing wallpaper
  src/Background/BackgroundSource.vala
Labels: Priority: High, Bitesize

#1262 Release 6.2.1
  data/gala.appdata.xml.in
  meson.build
Labels: Priority: High, Release

#1255 autostarts: set hidden under systemd
  data/gala-daemon.desktop
  data/gala-wayland.desktop
  data/gala.desktop
Labels: Bitesize
